- name: Fedora | Install kubernetes master
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: kubernetes-master
    state: latest
    enablerepo: "updates-testing"
  notify:
    - restart daemons
  when: not is_atomic
