---
- name: restart daemons
  command: /bin/true
  notify:
          - restart apiserver
          - restart controller-manager
          - restart scheduler

- name: restart apiserver
  service: name=kube-apiserver state=restarted

- name: restart controller-manager
  service: name=kube-controller-manager state=restarted

- name: restart scheduler
  service: name=kube-scheduler state=restarted

- name: restart iptables
  service: name=iptables state=restarted

- name: remove certs
  file: path={{ item }} state=absent
  with_items:
    - /srv/kubernetes/server.cert
    - /srv/kubernetes/server.key
