---
- name: DNS | Assures /etc/kubernetes/addons/dns dir exists
  file: path=/etc/kubernetes/addons/dns state=directory
  tags: dns

- name: DNS | Download skydns-rc.yaml file from Kubernetes repo
  local_action: get_url
    url=https://raw.githubusercontent.com/GoogleCloudPlatform/kubernetes/master/cluster/addons/dns/skydns-rc.yaml.in 
    dest=/tmp/kubernetes/addons/dns/skydns-rc.yaml.j2 mode=0755 owner=root group=root
  sudo: no
  tags: dns

- name: DNS | Convert pillar vars to ansible vars for skydns-rc.yaml
  local_action: replace
    dest=/tmp/kubernetes/addons/dns/skydns-rc.yaml.j2
    regexp="pillar\[\'(\w*)\'\]"
    replace="\1"
  sudo: no
  tags: dns

- name: DNS | Install Template from converted saltfile
  template: src=/tmp/kubernetes/addons/dns/skydns-rc.yaml.j2 dest=/etc/kubernetes/addons/dns/skydns-rc.yaml
  tags: dns

- name: DNS | Download skydns-svc.yaml file from Kubernetes repo
  local_action: get_url
    url=https://raw.githubusercontent.com/GoogleCloudPlatform/kubernetes/master/cluster/addons/dns/skydns-svc.yaml.in
    dest=/tmp/kubernetes/addons/dns/skydns-svc.yaml.j2 mode=0755 owner=root group=root
  sudo: no
  tags: dns

- name: DNS | Convert pillar vars to ansible vars for skydns-rc.yaml
  local_action: replace
    dest=/tmp/kubernetes/addons/dns/skydns-svc.yaml.j2
    regexp="pillar\[\'(\w*)\'\]"
    replace="\1"
  sudo: no
  tags: dns

- name: DNS | Install Template from converted saltfile
  template: src=/tmp/kubernetes/addons/dns/skydns-svc.yaml.j2 dest=/etc/kubernetes/addons/dns/skydns-svc.yaml
  tags: dns

- name: DNS | Check if the DNS pod exists
  shell: kubectl get rc kube-dns-v2
  register: has_dns_pod
  failed_when: false
  changed_when: false
  tags: dns

- name: DNS | Create SkyDNS pod
  shell: kubectl create -f /etc/kubernetes/addons/dns/skydns-rc.yaml
  when: dns_setup and has_dns_pod.rc != 0
  tags: dns

- name: DNS | Update DNS replication service
  shell: kubectl update -f /etc/kubernetes/addons/dns/skydns-rc.yaml
  when: dns_setup and has_dns_pod.rc == 0
  tags: dns

- name: DNS | Check that the DNS service exists
  shell: kubectl get service kube-dns
  register: has_dns_service
  failed_when: false
  changed_when: false
  tags: dns

- name: DNS | Create SkyDNS service
  shell: kubectl create -f /etc/kubernetes/addons/dns/skydns-svc.yaml
  when: dns_setup and has_dns_service.rc != 0
  tags: dns

- name: DNS | Update SkyDNS service
  shell: kubectl update -f /etc/kubernetes/addons/dns/skydns-svc.yaml
  when: dns_setup and has_dns_service.rc == 0
  tags: dns

