---
- name: DNS | Assures /etc/kubernetes/addons/dns dir exists
  file: path=/etc/kubernetes/addons/dns state=directory
  tags: dns

- name: DNS | Assures local dns addon dir exists
  local_action: file 
    path={{ local_temp_addon_dir }}/dns
    state=directory
  sudo: no
  tags: dns

- name: DNS | Download skydns-rc.yaml file from Kubernetes repo
  local_action: get_url
    url=https://raw.githubusercontent.com/GoogleCloudPlatform/kubernetes/master/cluster/addons/dns/skydns-rc.yaml.in 
    dest="{{ local_temp_addon_dir }}/dns/skydns-rc.yaml.j2" 
  sudo: no
  tags: dns

- name: DNS | Convert pillar vars to ansible vars for skydns-rc.yaml
  local_action: replace
    dest="{{ local_temp_addon_dir }}/dns/skydns-rc.yaml.j2"
    regexp="pillar\[\'(\w*)\'\]"
    replace="\1"
  sudo: no
  tags: dns

- name: DNS | Install Template from converted saltfile
  template: src="{{ local_temp_addon_dir }}/dns/skydns-rc.yaml.j2" dest=/etc/kubernetes/addons/dns/skydns-rc.yaml
    mode=0755 owner=root group=root
  notify:
    - update kube-addons
  tags: dns

- name: DNS | Download skydns-svc.yaml file from Kubernetes repo
  local_action: get_url
    url=https://raw.githubusercontent.com/GoogleCloudPlatform/kubernetes/master/cluster/addons/dns/skydns-svc.yaml.in
    dest="{{ local_temp_addon_dir }}/dns/skydns-svc.yaml.j2" 
  sudo: no
  tags: dns

- name: DNS | Convert pillar vars to ansible vars for skydns-rc.yaml
  local_action: replace
    dest="{{ local_temp_addon_dir }}/dns/skydns-svc.yaml.j2"
    regexp="pillar\[\'(\w*)\'\]"
    replace="\1"
  sudo: no
  tags: dns

- name: DNS | Install Template from converted saltfile
  template: src="{{ local_temp_addon_dir }}/dns/skydns-svc.yaml.j2" dest=/etc/kubernetes/addons/dns/skydns-svc.yaml
    mode=0755 owner=root group=root
  notify:
    - update kube-addons
  tags: dns
